services:
  gotify:
    image: gotify/server
    ports:
      - 8087:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'admin'
    volumes:
      - /mnt/qnap/docker_services/gotify/gotify_data:/app/data
    # to run gotify as a dedicated user:
    # sudo chown -R 1234:1234 ./gotify_data
    # user: "1234:1234"
    restart: always