services:
  grafana:
    image: grafana/grafana-enterprise
    labels:
      - wud.trigger=dockercompose:grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
    - /mnt/qnap/docker_services/grafana/data:/var/lib/grafana # chmod -R 777 /mnt/qnap/docker_services/grafana/data
# volumes:
#   grafana-storage: {}